### ISSUE TITLE
(TODO) encapsulate repeating backend code

### ISSUE THREAD

**Issue by im-fiv** [im-fiv/omeba-project#1]
Encapsulate repeating code into functions such as:
- [ ] checking user authentication and voiding invalid sessions
- [ ] general database interactions
- [ ] and more (if applicable)
